app:
  name: 'my_money'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'

db:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: my_money_purchases
    ssl: disable
    debug: true
    max_idle: 1
    max_open: 1

rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'
  url: "amqp://user:password@localhost:5672"
  user: user
  password: password
  port: 5672
  host: localhost
  queue: "test"
  exchange: "test"
  consumer_tag: "local_debug"

